runtime: python39

# App Engine configuration for Streamlit
env_variables:
  # Set production mode
  DEV_MODE: "False"
  # Ensure Streamlit can find secrets
  STREAMLIT_SERVER_HEADLESS: "true"
  STREAMLIT_BROWSER_GATHER_USAGE_STATS: "false"

# Automatic scaling configuration
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

# Resource allocation
resources:
  cpu: 1
  memory_gb: 2

# Handler for the main application
handlers:
- url: /.*
  script: auto
  secure: always